### ISSUE TITLE
Improve MiniDS CI/CD (continuous integration & deployment) on GitHub.

### ISSUE THREAD

**Issue by patudom** [cosmicds/minids#143]
- [x] Add end to end testing
- [ ] Add Nightwatch test for Pinwheel Supernova story

**Comment by Carifio24** [comment]
@patudom We actually do have end-to-end testing set up already - we have BrowserStack integration which runs for PRs and pushes to main. The tests themselves and the various runners are located in the `tests` directory, while the specific BrowserStack action stuff is in the workflow files.

The one current gap in this is that we don't have an E2E test for the Pinwheel Supernova test - I just haven't gotten around to writing a test since that story was finalized.

**Comment by Carifio24** [comment]
Closing this in favor of the new issues on each of the individual story repositories.
